import sys
sys.path.insert(0, '.')
import hyrcan as hy
import numpy as np
import csv, math, os

# ══════════════════════════════════════════════════════════════════
# CONFIGURATION
# Set MODE before running:
#   'seed'  — generate the initial LHS-300 Spencer dataset
#             (initial_lhs_300_spencer.csv); run this first.
#   'batch' — run the three surrogate-guided sets from hyrcan_arrays.py
#             (results_uniform.csv, results_lhs.csv, results_test.csv);
#             requires hyrcan_arrays.py generated by the Colab notebook.
# ══════════════════════════════════════════════════════════════════
MODE   = 'seed'    # <-- change to 'batch' after seed is complete
METHOD = 'Spencer'
SEED   = 42

param_ranges = {
    'angle': (10.0, 65.0),
    'phi':   (5.0,  40.0),
    'c':     (1.0,  75.0),
    'gamma': (14.0, 22.0),
    'H':     (1.0,  25.0),
}
PARAMS  = ['angle', 'phi', 'c', 'gamma', 'H']
COLUMNS = PARAMS + ['FOS', 'Center_X', 'Center_Y', 'Radius',
                    'At_Boundary', 'slope_length', 'extension', 'depth']

SEED_FILE  = 'initial_lhs_300_spencer.csv'
SEED_N     = 300


# ── Adaptive geometry ─────────────────────────────────────────────
def model_dims(H, angle, ext_factor=None, depth_factor=None):
    slope        = math.tan(angle * math.pi / 180)
    slope_length = H / slope
    extension    = max(1.5 * H, slope_length * 0.5)
    depth        = max(H, 0.5 * slope_length)
    if ext_factor:
        extension *= ext_factor
    if depth_factor:
        depth *= depth_factor
    return slope, slope_length, extension, depth


def initialize_model(H, angle, phi, c, gamma):
    slope, slope_length, extension, depth = model_dims(H, angle)
    cmd = f"""
    newmodel()
    set('failureDir','r2l')
    extboundary(-{depth},-{depth},-{depth},0,0,0,{slope_length},{H},{slope_length + extension},{H},{slope_length + extension},-{depth},-{depth},-{depth})
    definemat('ground','matID',1,'matName','Soil','uw',{gamma},'cohesion',{c},'friction',{phi})
    assignsoilmat('matid',1,'atpoint',{slope_length/2},{H/2})
    definelimits('limit',-{depth},{H/3/slope},'limit2',{2*H/3/slope},{slope_length + extension})
    set('Method','{METHOD}','on')
    """
    return cmd


# ── Critical surface QC ───────────────────────────────────────────
def find_intersection(cx, cy, r, y):
    if abs(cy - y) > r:
        return None
    dx = math.sqrt(r**2 - (cy - y)**2)
    return (cx - dx, cx + dx)


def check_boundary(cx, cy, r, H, angle, ext_factor=None, depth_factor=None):
    _, slope_length, extension, depth = model_dims(H, angle, ext_factor, depth_factor)
    tol = 0.01 * H
    flags = []
    gi = find_intersection(cx, cy, r, 0)
    if gi and abs(gi[0] - (-depth)) < tol:
        flags.append('left_lower')
    ti = find_intersection(cx, cy, r, H)
    if ti and abs(ti[1] - (slope_length + extension)) < tol:
        flags.append('right_upper')
    if cy - r < -depth:
        flags.append('below_domain')
    return bool(flags), flags


# ── FOS calculation ───────────────────────────────────────────────
def calculate_fos(angle, phi, c, gamma, H):
    try:
        _, slope_length, extension, depth = model_dims(H, angle)
        hy.command(initialize_model(H, angle, phi, c, gamma))
        hy.command("compute('silence')")
        fos    = hy.min_fos(METHOD)
        center = hy.surf_center_min_fos(METHOD)
        cx, cy = center[0], center[1]
        r      = hy.surf_radius_min_fos(METHOD)
        at_b, flags = check_boundary(cx, cy, r, H, angle)
        if at_b:
            print(f'  WARNING boundary: {flags}')
        return fos, cx, cy, r, at_b
    except Exception as e:
        print(f'  ERROR: {e}')
        import traceback; traceback.print_exc()
        return None, None, None, None, None


# ── LHS sampling ──────────────────────────────────────────────────
def generate_lhs(n, ranges, seed):
    from scipy.stats import qmc
    sampler = qmc.LatinHypercube(d=len(ranges), seed=seed)
    lo = np.array([v[0] for v in ranges.values()])
    hi = np.array([v[1] for v in ranges.values()])
    return qmc.scale(sampler.random(n), lo, hi)


# ── Generic batch runner (resume-aware) ───────────────────────────
def run_batch(combos, outfile, label):
    """Run Spencer analyses for a list of parameter combinations,
    writing results to outfile. Resumes from last completed row."""
    done = 0
    if os.path.exists(outfile):
        with open(outfile) as f:
            done = sum(1 for _ in f) - 1
        print(f'[{label}] Resume: {done}/{len(combos)} already computed.')
    else:
        with open(outfile, 'w', newline='') as f:
            csv.writer(f).writerow(COLUMNS)

    for i in range(done, len(combos)):
        angle, phi, c, gamma, H = combos[i]
        _, sl, ext, dep = model_dims(H, angle)
        print(f'\n[{label} {i+1}/{len(combos)}] '
              f'angle={angle:.1f} phi={phi:.1f} '
              f'c={c:.1f} gamma={gamma:.1f} H={H:.1f}')

        fos, cx, cy, r, at_b = calculate_fos(angle, phi, c, gamma, H)

        if fos is None:
            row = [angle, phi, c, gamma, H, '', '', '', '', '',
                   round(sl, 2), round(ext, 2), round(dep, 2)]
            print('  ERROR — NaN row written.')
        else:
            row = [angle, phi, c, gamma, H, round(fos, 4),
                   round(cx, 3), round(cy, 3), round(r, 3), at_b,
                   round(sl, 2), round(ext, 2), round(dep, 2)]
            print(f'  FOS = {fos:.3f}')

        with open(outfile, 'a', newline='') as f:
            csv.writer(f).writerow(row)

    print(f'\n=== [{label}] complete -> {outfile} ===')


# ── Single-case utility ───────────────────────────────────────────
def run_single(angle, phi, c, gamma, H):
    """Run a single Spencer analysis and print full result details."""
    _, sl, ext, dep = model_dims(H, angle)
    print(f'Parameters:  angle={angle} phi={phi} c={c} gamma={gamma} H={H}')
    print(f'Geometry:    slope_length={sl:.3f} extension={ext:.3f} depth={dep:.3f}')
    fos, cx, cy, r, at_b = calculate_fos(angle, phi, c, gamma, H)
    if fos is None:
        print('ERROR: solver did not return a FOS value.')
        return
    print(f'FOS:         {fos:.4f}')
    print(f'Surface:     center=({cx:.3f}, {cy:.3f})  radius={r:.3f}')
    print(f'At_Boundary: {at_b}')


# ── Main ──────────────────────────────────────────────────────────
def main():
    if MODE == 'seed':
        # ── Stage 1: generate the initial LHS-300 seed dataset ───
        print(f'MODE=seed — generating {SEED_N}-point LHS seed '
              f'(SEED={SEED}) -> {SEED_FILE}')
        samples = generate_lhs(SEED_N, param_ranges, SEED)
        run_batch(samples, SEED_FILE, 'seed')

    elif MODE == 'batch':
        # ── Stage 3: run surrogate-guided sets from Colab ─────────
        # Requires hyrcan_arrays.py produced by the Colab notebook.
        if not os.path.exists('hyrcan_arrays.py'):
            raise FileNotFoundError(
                'hyrcan_arrays.py not found. '
                'Run the Colab notebook (02_surrogate_selection.ipynb) '
                'and place hyrcan_arrays.py in this directory.')
        from hyrcan_arrays import uniform_train_300, test_150, lhs_300
        sets = {
            'uniform': uniform_train_300,
            'lhs':     lhs_300,
            'test':    test_150,
        }
        for set_name, combos in sets.items():
            run_batch(combos, f'results_{set_name}.csv', set_name)

    else:
        raise ValueError(f"Unknown MODE '{MODE}'. Use 'seed' or 'batch'.")


if __name__ == '__main__':
    main()

    # data = [74.88293778099170, 38.79434845458250, 46.19642169922790, 17.014196515354600, 24.279498507950400]
    # run_single(angle=data[0], phi=data[1], c=data[2], gamma=data[3], H=data[4])